//! Issue integration — create/update issues from agent findings.
//!
//! Supports creating issues in external trackers from RCA findings,
//! index health reports, and anomaly detections.  Currently supports:
//!
//! - **GitHub Issues**: via `gh` CLI or GitHub API
//! - **`PostgresAI` Issues**: via MCP tool bridge (runtime-provided)
//!
//! Template-based issue content ensures consistent formatting.

// Phase 3 infrastructure — consumers arrive in subsequent PRs.
#![allow(dead_code)]

use std::fmt::Write as _;

use crate::governance::{ActionProposal, Severity};

// ---------------------------------------------------------------------------
// Issue template
// ---------------------------------------------------------------------------

/// A structured issue ready to be created in an external tracker.
#[derive(Debug, Clone)]
pub struct IssueTemplate {
    /// Issue title (short summary).
    pub title: String,
    /// Issue body (Markdown).
    pub body: String,
    /// Labels to apply.
    pub labels: Vec<String>,
    /// Source feature area.
    pub source: String,
}

// ---------------------------------------------------------------------------
// GitHub Issues
// ---------------------------------------------------------------------------

/// GitHub Issues integration via the `gh` CLI.
#[derive(Debug)]
pub struct GitHubIssueCreator {
    /// Repository in `owner/repo` format.
    repo: String,
}

impl GitHubIssueCreator {
    /// Create a new GitHub issue creator for the given repository.
    pub fn new(repo: String) -> Self {
        Self { repo }
    }

    /// Create a GitHub issue using the `gh` CLI.
    ///
    /// Returns the issue URL on success, or an error message.
    pub async fn create_issue(&self, template: &IssueTemplate) -> Result<String, String> {
        let repo = self.repo.clone();
        let title = template.title.clone();
        let body = template.body.clone();
        let labels = template.labels.clone();

        tokio::task::spawn_blocking(move || {
            let mut cmd = std::process::Command::new("gh");
            cmd.args(["issue", "create", "--repo", &repo]);
            cmd.args(["--title", &title]);
            cmd.args(["--body", &body]);
            for label in &labels {
                cmd.args(["--label", label]);
            }

            let output = cmd
                .output()
                .map_err(|e| format!("Failed to run `gh` CLI (is it installed?): {e}"))?;

            if output.status.success() {
                let url = String::from_utf8_lossy(&output.stdout).trim().to_owned();
                Ok(url)
            } else {
                let stderr = String::from_utf8_lossy(&output.stderr).trim().to_owned();
                Err(format!("gh issue create failed: {stderr}"))
            }
        })
        .await
        .map_err(|e| format!("Task join error: {e}"))?
    }
}

// ---------------------------------------------------------------------------
// Template builders
// ---------------------------------------------------------------------------

/// Build an issue template from an RCA snapshot.
pub fn issue_from_rca(
    dbname: &str,
    anomaly_summary: &str,
    diagnostic_steps: &[(String, bool)],
) -> IssueTemplate {
    let mut body = String::new();
    writeln!(body, "## RCA Report — {dbname}").unwrap();
    writeln!(body).unwrap();
    writeln!(body, "**Anomaly:** {anomaly_summary}").unwrap();
    writeln!(body).unwrap();
    writeln!(body, "### Diagnostic Steps").unwrap();
    writeln!(body).unwrap();
    for (step_name, has_data) in diagnostic_steps {
        let icon = if *has_data {
            "data collected"
        } else {
            "no data"
        };
        writeln!(body, "- **{step_name}**: {icon}").unwrap();
    }
    writeln!(body).unwrap();
    writeln!(body, "---").unwrap();
    writeln!(body, "*Auto-generated by Rpg*").unwrap();

    IssueTemplate {
        title: format!("[Rpg] RCA: {anomaly_summary}"),
        body,
        labels: vec![
            "rpg".to_owned(),
            "rca".to_owned(),
            "auto-generated".to_owned(),
        ],
        source: "rca".to_owned(),
    }
}

/// Build an issue template from action proposals.
pub fn issue_from_proposals(dbname: &str, proposals: &[ActionProposal]) -> Option<IssueTemplate> {
    if proposals.is_empty() {
        return None;
    }

    let max_severity = proposals
        .iter()
        .map(|p| p.severity)
        .max()
        .unwrap_or(Severity::Info);

    let severity_label = match max_severity {
        Severity::Critical => "critical",
        Severity::Warning => "warning",
        Severity::Info => "info",
    };

    let feature = proposals[0].feature.label();

    let mut body = String::new();
    writeln!(body, "## Findings — {dbname}").unwrap();
    writeln!(body).unwrap();
    writeln!(
        body,
        "Rpg detected **{count}** actionable finding(s) in the `{feature}` area.",
        count = proposals.len(),
    )
    .unwrap();
    writeln!(body).unwrap();

    for (i, p) in proposals.iter().enumerate() {
        let sev = match p.severity {
            Severity::Critical => "!!",
            Severity::Warning => "!",
            Severity::Info => " ",
        };
        writeln!(body, "### {sev} Finding {}", i + 1).unwrap();
        writeln!(body).unwrap();
        writeln!(body, "**Problem:** {}", p.finding).unwrap();
        writeln!(body, "**Proposed action:** `{}`", p.proposed_action).unwrap();
        writeln!(body, "**Expected outcome:** {}", p.expected_outcome).unwrap();
        writeln!(body, "**Risk:** {}", p.risk).unwrap();
        writeln!(body).unwrap();
    }

    writeln!(body, "---").unwrap();
    writeln!(body, "*Auto-generated by Rpg*").unwrap();

    Some(IssueTemplate {
        title: format!(
            "[Rpg] {feature}: {count} finding(s) on {dbname}",
            count = proposals.len()
        ),
        body,
        labels: vec![
            "rpg".to_owned(),
            feature.to_owned(),
            severity_label.to_owned(),
            "auto-generated".to_owned(),
        ],
        source: feature.to_owned(),
    })
}

/// Build an issue template from an anomaly detection.
pub fn issue_from_anomaly(dbname: &str, anomaly_kind: &str, description: &str) -> IssueTemplate {
    let mut body = String::new();
    writeln!(body, "## Anomaly Detected — {dbname}").unwrap();
    writeln!(body).unwrap();
    writeln!(body, "**Type:** {anomaly_kind}").unwrap();
    writeln!(body, "**Description:** {description}").unwrap();
    writeln!(body).unwrap();
    writeln!(body, "---").unwrap();
    writeln!(body, "*Auto-generated by Rpg daemon*").unwrap();

    IssueTemplate {
        title: format!("[Rpg] Anomaly: {anomaly_kind} on {dbname}"),
        body,
        labels: vec![
            "rpg".to_owned(),
            "anomaly".to_owned(),
            "auto-generated".to_owned(),
        ],
        source: "anomaly".to_owned(),
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::governance::{EvidenceClass, FeatureArea};

    #[test]
    fn issue_from_rca_has_title_and_body() {
        let steps = vec![
            ("Lock tree".to_owned(), true),
            ("Wait events".to_owned(), false),
        ];
        let issue = issue_from_rca("prod", "Lock cascade detected", &steps);
        assert!(issue.title.contains("RCA"));
        assert!(issue.title.contains("Lock cascade"));
        assert!(issue.body.contains("prod"));
        assert!(issue.body.contains("data collected"));
        assert!(issue.body.contains("no data"));
        assert!(issue.labels.contains(&"rca".to_owned()));
    }

    #[test]
    fn issue_from_proposals_none_when_empty() {
        assert!(issue_from_proposals("db", &[]).is_none());
    }

    #[test]
    fn issue_from_proposals_formats_findings() {
        let proposals = vec![
            ActionProposal {
                feature: FeatureArea::IndexHealth,
                severity: Severity::Warning,
                evidence_class: EvidenceClass::Heuristic,
                finding: "idx_foo is unused".to_owned(),
                proposed_action: "DROP INDEX CONCURRENTLY idx_foo".to_owned(),
                expected_outcome: "Free 100MB".to_owned(),
                risk: "Low".to_owned(),
                created_at: std::time::SystemTime::now(),
            },
            ActionProposal {
                feature: FeatureArea::IndexHealth,
                severity: Severity::Critical,
                evidence_class: EvidenceClass::Factual,
                finding: "idx_bar is invalid".to_owned(),
                proposed_action: "REINDEX CONCURRENTLY idx_bar".to_owned(),
                expected_outcome: "Restore index".to_owned(),
                risk: "Low".to_owned(),
                created_at: std::time::SystemTime::now(),
            },
        ];
        let issue = issue_from_proposals("prod", &proposals).unwrap();
        assert!(issue.title.contains("2 finding(s)"));
        assert!(issue.body.contains("idx_foo"));
        assert!(issue.body.contains("idx_bar"));
        // Max severity is Critical.
        assert!(issue.labels.contains(&"critical".to_owned()));
    }

    #[test]
    fn issue_from_anomaly_formats_correctly() {
        let issue = issue_from_anomaly("staging", "SessionSpike", "Active sessions jumped to 150");
        assert!(issue.title.contains("SessionSpike"));
        assert!(issue.body.contains("staging"));
        assert!(issue.body.contains("150"));
        assert!(issue.labels.contains(&"anomaly".to_owned()));
    }

    #[test]
    fn github_issue_creator_stores_repo() {
        let creator = GitHubIssueCreator::new("owner/repo".to_owned());
        assert_eq!(creator.repo, "owner/repo");
    }

    #[test]
    fn issue_template_labels_are_not_empty() {
        let issue = issue_from_rca("db", "test", &[]);
        assert!(!issue.labels.is_empty());
        assert!(issue.labels.contains(&"rpg".to_owned()));
    }

    #[test]
    fn issue_from_proposals_single_info_severity() {
        let proposals = vec![ActionProposal {
            feature: FeatureArea::ConfigTuning,
            severity: Severity::Info,
            evidence_class: EvidenceClass::Heuristic,
            finding: "timeout disabled".to_owned(),
            proposed_action: "ALTER SYSTEM SET statement_timeout = '30s'".to_owned(),
            expected_outcome: "Queries capped at 30s".to_owned(),
            risk: "Moderate".to_owned(),
            created_at: std::time::SystemTime::now(),
        }];
        let issue = issue_from_proposals("dev", &proposals).unwrap();
        assert!(issue.labels.contains(&"info".to_owned()));
        assert!(issue.title.contains("1 finding(s)"));
    }
}
